export const enum SceneNames {
  LoginScreen = "LoginScreen",
  RegistrationScreen = "RegistrationScreen",
  DestinationScreen = "DestinationScreen",
  GuestsScreen = "GuestsScreen",
  SearchResultsScreen = "SearchResultsScreen",
  HotelDetailScreen = "HotelDetailScreen",
  RoomListScreen = "RoomListScreen",
  RoomDetailScreen = "RoomDetailScreen",
  RoomViewScreen = "RoomViewScreen",
  GuestDetailScreen = "GuestDetailScreen",
  CheckoutScreen = "CheckoutScreen",
  BookingDetailScreen = "BookingDetailScreen",
  ThankYouScreen = "ThankYouScreen",
  WebViewScreen = "WebViewScreen",
  CalendarScreen = "CalendarScreen",
  AmenitiesScreen = "AmenitiesScreen",
  AppNavigator = "AppNavigator",
  HomeScreen = "HomeScreen",
  HotelNearByScreen = "HotelNearByScreen",
  ProfileScreen = "ProfileScreen",
  BookingsScreen = "BookingsScreen",
  ComfirmScreen = "ComfirmScreen",
  ResetPasswordScreen = "ResetPasswordScreen"
}