/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "eu-west-1",
  "aws_cognito_identity_pool_id": "eu-west-1:bcf2c4e0-5a99-42e4-b359-810cc8d48e38",
  "aws_cognito_region": "eu-west-1",
  "aws_user_pools_id": "eu-west-1_WYZfYKelO",
  "aws_user_pools_web_client_id": "6c20lgiebk7fr54i2mdb0c44a",
  "oauth": {
    "domain": "getroomsapp7d72cd98-7d72cd98-dev.auth.eu-west-1.amazoncognito.com",
    "scope": [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin"
    ],
    "redirectSignIn": "myapp://getroomsapp7d72cd98-7d72cd98-dev.auth.eu-west-1.amazoncognito.com/oauth2/idpresponse/",
    "redirectSignOut": "myapp://getroomsapp7d72cd98-7d72cd98-dev.auth.eu-west-1.amazoncognito.com/oauth2/idpresponse/",
    "responseType": "code"
  },
  "federationTarget": "COGNITO_USER_POOLS"
}


export default awsmobile
